name: 'lint my project'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_lint:
    runs-on: ubuntu-latest
    steps:
    - name: lint
      run: make lint
    
